export default {
    properties:[
        {
        _id:'1',
        contact_person:'Sai Teja',
        contact_number:9866169957,
        image:'/images/img1.jpg',
        place:'Adilabad',
        address:'Adilabad Telangana India 18 Lac(s)',
        mail:'sait0662@gmail.com',
        Area:'2000 sft',
        Size:'40*50',
    },
    {
        _id:'2',
        contact_person:'Sai Teja',
        contact_number:9866169957,
        image:'/images/img1.jpg',
        place:'Adilabad',
        address:'Adilabad Telangana India 18 Lac(s)',
        mail:'sait0662@gmail.com',
        Area:'2000 sft',
        Size:'40*50',
    },
    {
        _id:'3',
        contact_person:'Sai Teja',
        contact_number:9866169957,
        image:'/images/img1.jpg',
        place:'Adilabad',
        address:'Adilabad Telangana India 18 Lac(s)',
        mail:'sait0662@gmail.com',
        Area:'2000 sft',
        Size:'40*50',
    },
    {
        _id:'4',
        contact_person:'Sai Teja',
        contact_number:9866169957,
        image:'/images/img1.jpg',
        place:'Adilabad',
        address:'Adilabad Telangana India 18 Lac(s)',
        mail:'sait0662@gmail.com',
        Area:'2000 sft',
        Size:'40*50',
    },
    {
        _id:'5',
        contact_person:'Sai Teja',
        contact_number:9866169957,
        image:'/images/img1.jpg',
        place:'Adilabad',
        address:'Adilabad Telangana India 18 Lac(s)',
        mail:'sait0662@gmail.com',
        Area:'2000 sft',
        Size:'40*50',
    },
    {
        _id:'6',
        contact_person:'Sai Teja',
        contact_number:9866169957,
        image:'/images/img1.jpg',
        place:'Adilabad',
        address:'Adilabad Telangana India 18 Lac(s)',
        mail:'sait0662@gmail.com',
        Area:'2000 sft',
        Size:'40*50',
    },
    {
        _id:'7',
        contact_person:'Sai Teja',
        contact_number:9866169957,
        image:'/images/img1.jpg',
        place:'Adilabad',
        address:'Adilabad Telangana India 18 Lac(s)',
        mail:'sait0662@gmail.com',
        Area:'2000 sft',
        Size:'40*50',
    },
    {
        _id:'8',
        contact_person:'Sai Teja',
        contact_number:9866169957,
        image:'/images/img1.jpg',
        place:'Adilabad',
        address:'Adilabad Telangana India 18 Lac(s)',
        mail:'sait0662@gmail.com',
        Area:'2000 sft',
        Size:'40*50',
    },
    {
        _id:'9',
        contact_person:'Sai Teja',
        contact_number:9866169957,
        image:'/images/img1.jpg',
        place:'Adilabad',
        address:'Adilabad Telangana India 18 Lac(s)',
        mail:'sait0662@gmail.com',
        Area:'2000 sft',
        Size:'40*50',
    },
    {
        _id:'10',
        contact_person:'Sai Teja',
        contact_number:9866169957,
        image:'/images/img1.jpg',
        place:'Adilabad',
        address:'Adilabad Telangana India 18 Lac(s)',
        mail:'sait0662@gmail.com',
        Area:'2000 sft',
        Size:'40*50',
    },
    {
        _id:'11',
        contact_person:'Sai Teja',
        contact_number:9866169957,
        image:'/images/img1.jpg',
        place:'Adilabad',
        address:'Adilabad Telangana India 18 Lac(s)',
        mail:'sait0662@gmail.com',
        Area:'2000 sft',
        Size:'40*50',
    },
    {
        _id:'12',
        contact_person:'Sai Teja',
        contact_number:9866169957,
        image:'/images/img1.jpg',
        place:'Adilabad',
        address:'Adilabad Telangana India 18 Lac(s)',
        mail:'sait0662@gmail.com',
        Area:'2000 sft',
        Size:'40*50',
    },

]
}

